CREATE TABLE hearsay_reviews (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    state TEXT NOT NULL,
    department TEXT NOT NULL,
    nature TEXT NOT NULL,
    rating INTEGER NOT NULL,
    date TIMESTAMPTZ DEFAULT now() NOT NULL,
    comments TEXT
);

CREATE TABLE hearsay_users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_name TEXT NOT NULL UNIQUE,
  full_name TEXT NOT NULL,
  password TEXT NOT NULL,
  nick_name TEXT,
  date_created TIMESTAMPTZ NOT NULL DEFAULT now(),
  date_modified TIMESTAMPTZ
);

ALTER TABLE hearsay_reviews 
  ADD COLUMN
    user_id INTEGER REFERENCES hearsay_users(id)
      ON DELETE SET NULL;

CREATE TABLE hearsay_discussion (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    discussion_post TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    user_id INTEGER
        REFERENCES hearsay_users(id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE hearsay_topics (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    topic_name TEXT NOT NULL UNIQUE
);


ALTER TABLE hearsay_discussion 
    ADD COLUMN
        topic_name TEXT REFERENCES hearsay_topics(topic_name) ON DELETE CASCADE NOT NULL;

ALTER TABLE hearsay_reviews
    ADD COLUMN 
        incident_date DATE DEFAULT now() NOT NULL;

ALTER TABLE hearsay_reviews
    DROP COLUMN date;

ALTER TABLE hearsay_reviews
    ADD COLUMN review_date TIMESTAMPTZ DEFAULT now() NOT NULL;