CREATE TABLE hearsay_reviews (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    state TEXT NOT NULL,
    department TEXT NOT NULL,
    nature TEXT NOT NULL,
    rating INTEGER NOT NULL,
    date TIMESTAMPTZ DEFAULT now() NOT NULL,
    comments TEXT
);