  
CREATE TABLE hearsay_users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_name TEXT NOT NULL UNIQUE,
  full_name TEXT NOT NULL,
  password TEXT NOT NULL,
  nick_name TEXT,
  date_created TIMESTAMPTZ NOT NULL DEFAULT now(),
  date_modified TIMESTAMPTZ
);

ALTER TABLE hearsay_reviews 
  ADD COLUMN
    user_id INTEGER REFERENCES hearsay_users(id)
      ON DELETE SET NULL;
