CREATE TABLE hearsay_discussion (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    discussion_post TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    user_id INTEGER
        REFERENCES hearsay_users(id) ON DELETE CASCADE NOT NULL
);